### ISSUE TITLE
alpaca-tunnel项目无法提交问题，所以在此提交，请谅解。在苹果机上，make遇错

### ISSUE THREAD

**Issue by briteming** [AlpacaTunnel/alpaca-go#1]
hi.

yudeMacBook-Air:alpaca-tunnel brite$ make
gcc -std=gnu11 main.c aes.c log.c peer.c ip.c vpn.c monitor.c signal.c header.c policy.c tunif.c cmd.c route.c config.c data-struct/*.c -lpthread -lm -o alpaca-tunnel -Wall -O3
main.c:6:10: fatal error: 'sys/inotify.h' file not found
#include <sys/inotify.h>
         ^
1 error generated.
make: *** [all] Error 1
yudeMacBook-Air:alpaca-tunnel brite$

如何解决？

**Comment by AlpacaTunnel** [comment]
抱歉，那个项目只支持Linux，并且代码写得太烂已经不维护了。
